config/routes.rb
# -*- encoding : utf-8 -*-
Grad::Application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  resources :groups do
    resources :pages
    post :sort, on: :collection
  end

  root :to => "home#index"
  devise_for :users, :controllers => {:registrations => "registrations"}

  resources :users

  get 'p/:address' => 'pages#see_page',:as=>:address

end

app/models/group.rb
# -*- encoding : utf-8 -*-
class Group < ActiveRecord::Base
  has_many :pages, :dependent => :destroy
  validates :name,presence: true, uniqueness: true, length:{ :in => 2..50 }
  before_validation :set_position,:on=>:create


  def set_position
    self.position=Group.maximum(:position).to_i+1 if self.position.blank?
  end
  
end

app/controllers/groups_controller.rb
# -*- encoding : utf-8 -*-
class GroupsController < ApplicationController
  before_action :set_group, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /groups
  # GET /groups.json
  def index
    @groups = Group.all.order("position")
  end

  # GET /groups/1
  # GET /groups/1.json
  def show
  end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # GET /groups/1/edit
  def edit
  end

  # POST /groups
  # POST /groups.json
  def create
    @group = Group.new(group_params)

    respond_to do |format|
      if @group.save
        format.html { redirect_to groups_path, notice: 'Группа успешно созданна.' }
        format.json { render action: 'show', status: :created, location: @group }
      else
        format.html { render action: 'new' }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1
  # PATCH/PUT /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to groups_path, notice: 'Информация о группе успешно отредактирована.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group.destroy
    respond_to do |format|
      format.html { redirect_to groups_url , notice: 'Группа успешно удалена.'}
      format.json { head :no_content }
    end
  end

    def sort
      params[:groups].each_with_index do |group_id,i|
        id = group_id.split('_').last
        next unless id
        Group.find_by(id: id).update_attribute(:position, i)
      end
       head :no_content
    end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group
      @group = Group.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def group_params
      params.require(:group).permit(:name, :address, :position, :color)
    end
end

app/helpers/groups_helper.rb
# -*- encoding : utf-8 -*-
module GroupsHelper
end

app/views/groups/_form.html.slim
= form_for @group do |f|
  - if @group.errors.any?
    #error_explanation
      h2 "#{pluralize(@group.errors.count, "error")} prohibited this group from being saved:"
      ul
        - @group.errors.full_messages.each do |msg|
          li =msg

  .col-md-5
    .form-group
      = f.label :name
      = f.text_field :name, class:"form-control"
    .form-group
      = f.label :address
      = f.text_field :address, class:"form-control"
    / .form-group
    /   = f.label :color
    /   -if @group.pages.size==0
    /     | У групы нет страниц
    /   -else
    /     = f.color_field :color, class:"form-control"  
    .actions
      = f.submit 'Сохранить' , class:"btn btn-success"
      = link_to 'Назад к списку групп', groups_path, class: "btn btn-danger"

app/views/groups/edit.html.slim
h1 Редактирование группы

= render 'form'

app/views/groups/index.html.slim
h1 Список групп

.pull-right
  -if current_user
    = link_to 'Новая группа', new_group_path, class:"btn btn-primary"

table.table.table-striped
  thead
    tr
      th Название
      th Адрес
      / th Цвет
      -if current_user
        th Действия

  tbody#sortable
    - @groups.each do |group|
      tr id="groups_#{group.id}"
        td= group.name
        td= group.address
        / td
        /   i.fa.fa-paint-brush style="color: #{group.color}"
        td

          -if current_user
            = link_to 'В группу', group_pages_path(group), class: "btn btn-success"
            = link_to 'Редактировать', edit_group_path(group), class: "btn btn-primary"
            = link_to 'Удалить', group, :method => :delete, :data => { :confirm => 'Удалить группу?' }, class: "btn btn-danger"

app/views/groups/new.html.slim
h1 Новая группа

= render 'form'

app/views/groups/show.html.slim
p#notice= notice

p
  b Название:
  = @group.name
p
  b Адрес:
  = @group.address

-if current_user
  = link_to 'Редактировать', edit_group_path(@group), class: "btn btn-primary  "

= link_to 'Назад', groups_path, class:  "btn btn-inverse"