config/routes.rb
# -*- encoding : utf-8 -*-
Grad::Application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  resources :groups do
    resources :pages
    post :sort, on: :collection
  end

  root :to => "home#index"
  devise_for :users, :controllers => {:registrations => "registrations"}

  resources :users

  get 'p/:address' => 'pages#see_page',:as=>:address

end

app/models/user.rb
# -*- encoding : utf-8 -*-
class User < ActiveRecord::Base
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/users_controller.rb
# -*- encoding : utf-8 -*-
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    authorize! :index, @user, :message => 'Not authorized as an administrator.'
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def update
    authorize! :update, @user, :message => 'Not authorized as an administrator.'
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user], :as => :admin)
      redirect_to users_path, :notice => "User updated."
    else
      redirect_to users_path, :alert => "Unable to update user."
    end
  end

  def destroy
    authorize! :destroy, @user, :message => 'Not authorized as an administrator.'
    user = User.find(params[:id])
    unless user == current_user
      user.destroy
      redirect_to users_path, :notice => "User deleted."
    else
      redirect_to users_path, :notice => "Can't delete yourself."
    end
  end
end

app/views/users/_user.html.slim
.modal id="role-options-#{user.id}" style='display: none;'
  = form_for user, :url => user_path(user), :html => {:method => :put, :class => 'form-horizontal' } do |f|
    .modal-header
      a.close{"data-dismiss" => "modal"} ×
      h3 Change Role
    .modal-body
      = collection_select :user, :role_ids, Role.all, :id, :name, checked: user.role_ids.first
    .modal-footer
      = f.submit "Change Role", :class => "btn"
      a.btn{"data-dismiss" => "modal", :href => "#"} Close

app/views/users/index.html.slim
h3 Users
.span8
  table.table.table-condensed
    thead
      tr
        th Username
        th Email
        th Registered
        th Role
        th
        th
    tbody
      - @users.each do |user|
        tr
          td= link_to user.name, user
          td= user.email
          td= user.created_at.to_date
          td= user.roles.first.name.titleize unless user.roles.first.nil?
          td
            a.btn.btn-mini{"data-toggle" => "modal", :href => "#role-options-#{user.id}", :type => "button"} Change role
            = render user
          td= link_to("Delete user", user_path(user), :data => { :confirm => "Are you sure?" }, :method => :delete, :class => 'btn btn-mini') unless user == current_user

app/views/users/show.html.slim
h3 User
p
  | User: #{@user.name}
p
  | Email: #{@user.email if @user.email}