config/routes.rb
# -*- encoding : utf-8 -*-
Grad::Application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  resources :groups do
    resources :pages
    post :sort, on: :collection
  end

  root :to => "home#index"
  devise_for :users, :controllers => {:registrations => "registrations"}

  resources :users

  get 'p/:address' => 'pages#see_page',:as=>:address

end

app/views/pages/_form.html.slim
= form_for [@group,@page] do |f|
  - if @page.errors.any?
    #error_explanation
      h2= "#{pluralize(@page.errors.count, "error")} prohibited this page from being saved:"
      ul
        - @page.errors.full_messages.each do |msg|
          li= msg
  .row
    .col-md-5
      .form-group
        = f.label :title
        = f.text_field :title, class:"form-control"
      .form-group
        = f.label :name
        = f.text_field :name, class:"form-control"
      .form-group
        = f.label :address
        = f.text_field :address, class:"form-control"
    .col-md-7
      .form-group
        = f.label :meta_key
        = f.text_field :meta_key, class:"form-control"
      .form-group
        = f.label :meta_des
        = f.text_field :meta_des, class:"form-control"
  .row
    .col-md-12
      .form-group
        = f.label :body
        = f.cktext_area :body, class: 'span8',:ckeditor => {filebrowserImageBrowseUrl: '/ckeditor/pictures', filebrowserImageUploadUrl: '/ckeditor/pictures',:uiColor => "#AADC6E", :toolbar => "Full"}


  .actions
    -if current_user
      = f.submit 'Сохранить' , class:"btn btn-success"
      = link_to 'Назад', group_pages_path(@group), class: "btn btn-danger"

app/views/pages/edit.html.slim
h1 Редактирование страницы

= render 'form'

app/views/pages/index.html.slim
h1 Список страниц

table.table.table-striped
  thead
    tr
      th Заголовок
      th Тело
      th Адрес
      th

  tbody
    - @pages.each do |page|
      tr
        td= page.title
        td= page.body[0..25]
        td= page.address
        td
          -if current_user
            div class='btn-group'
              =link_to "Открыть страницу", address_path(:address=>page.address), class: "btn btn-info", target: '_blank'
              a class='btn dropdown-toggle' data-toggle='dropdown'
                span.caret
              ul.dropdown-menu
                li= link_to 'Подробнее', group_page_path(@group,page)
                li= link_to 'Редактировать', edit_group_page_path(@group,page)
                li= link_to 'Удалить', group_page_path(@group,page), method: 'delete', data: { confirm: 'Вы уверены, что хотите удалить эту страницу?' }
          -else
            =link_to "Открыть страницу", address_path(:address=>page.address), class: "btn btn-info", target: '_blank'
br
-if current_user
  = link_to 'Новая страница', new_group_page_path(@group), class:"btn btn-primary"
  = link_to 'Назад к списку групп', groups_path, class:"btn btn-danger"

app/views/pages/new.html.slim
h1 Новая страница

= render 'form'

app/views/pages/show.html.slim
- content_for :meta do
  meta name='description' content="#{@page.meta_des}"
  meta name='keywords' content="#{@page.meta_key}"

-if current_user && @group.present? && @page.present?
  .edit-btn
    = link_to 'Редактировать', edit_group_page_path(@group,@page), role: "button", class: 'btn btn-primary'
    = link_to 'Перейти в группу страницы', group_pages_path(@group), role: "button", class: 'btn btn-success'

-if @group.present?
  -pages = @group.pages.order("created_at")
  -if pages.size>1
    .btn-group.btn-group-justified role="group" style="display:block; text-align: center;"
      -pages.each do |pag|
        = link_to pag.name, address_path(:address=>pag.address), class: "btn btn-#{ pag.id == @page.id ? 'primary' : 'default'}"
br

- content_for :title do
  =@page.title

= raw(@page.body)